export let product=[
{
          image:"image/01.png",
          id:"G001",
          name:"Classic",
          price:100,
          qty:1
},
{
          image:"image/02.png",
          id:"G002",
          name:"Shorty",
          price:200,
          qty:10
},
{
          image:"image/03.png",
          id:"G003",
          name:"Frenzy",
          price:400,
          qty:15
},
{
          image:"image/04.png",
          id:"G004",
          name:"Ghost",
          price:500,
          qty:8
},
{
          image:"image/05.png",
          id:"G005",
          name:"Sheriff",
          price:800,
          qty:5
},
{
          image:"image/06.png",
          id:"G006",
          name:"Stinger",
          price:1000,
          qty:10
},
{
          image:"image/07.png",
          id:"G007",
          name:"Spectre",
          price:1600,
          qty:9
},
{
          image:"image/08.png",
          id:"G008",
          name:"Bucky",
          price:900,
          qty:7
},
{
          image:"image/09.png",
          id:"G009",
          name:"Judge",
          price:1600,
          qty:6
},
{
          image:"image/010.png",
          id:"G010",
          name:"Bulldog",
          price:2100,
          qty:11
},
{
          image:"image/011.png",
          id:"G011",
          name:"Guardian",
          price:2500,
          qty:10
},
{
          image:"image/012.png",
          id:"G012",
          name:"Phantom",
          price:2900,
          qty:15
},
{
          image:"image/013.png",
          id:"G013",
          name:"Vandal",
          price:2900,
          qty:15
}];